language: cpp
dist: xenial
compiler: gcc

os:
  - linux
  # - osx

script:
  - sudo apt-get install cmake libhts-dev libtbb-dev -y
  - cd /usr/include && ls
  - cd /usr/libx86_64-linux-gnu && ls
  - cd /usr/ && ls
  - mkdir build && cd build && cmake .. -DINCLUDE_LIBRARY_PREFIX=/usr/include -DLIBRARY_LINK_PREFIX=/usr/x86_64-linux-gnu/
  - make
  - ./bin/bolt