name: Ubuntu
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Install Lib
        run: sudo apt-get install cmake libtbb-dev -y
      - uses: actions/checkout@v1
      - name: Configure
        run: mkdir build
      - name: export LD_LIBRARY_PATH
        run: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib/x86_64-linux-gnu/ && echo $LD_LIBRARY_PATH
      - name: Wget
        run: wget https://github.com/samtools/htslib/releases/download/1.10/htslib-1.10.tar.bz2 && tar -xvjf htslib-1.10.tar.bz2 && ls
      - name: Build htslib
        run: cd htslib-1.10 && autoheader && autoconf && ./configure && make && sudo make install
      - name: Include
        run: cd /usr/include && ls
      - name: Lib
        run: cd /usr/lib/x86_64-linux-gnu && ls
      - name: Lib
        run: cd /usr/ && ls
      - name: Lib
        run: cd /usr/local/ && ls
      - name: Lib
        run: cd /usr/lib/x86_64-linux-gnu/ && ls
      - name: Lib
        run: ldconfig -p | grep libhts
      - name: Build
        run: cd build && cmake .. -DINCLUDE_LIBRARY_PREFIX=/usr/include -DLIBRARY_LINK_PREFIX=/usr/lib/x86_64-linux-gnu  && make
      - name: Test
        run: cd build && make install
